### ISSUE TITLE
[style] is var(--topNavBarHeight) applied twice in default style?

### ISSUE THREAD

**Issue by whitedogg13** [revtel/gatsby-starter#116]
![image](https://user-images.githubusercontent.com/10307875/157187496-97e417fe-f0e9-4d8f-9927-a7555d090748.png)

**Comment by Mylio-chang** [comment]
issue fixed in starter
https://github.com/revtel/gatsby-starter/pull/83/commits/8813a8a5d73a3862502ae6a99493f596aed092c9
