### ISSUE TITLE
[feat] use `useAntdTable` for order  

### ISSUE THREAD

**Issue by whitedogg13** [revtel/gatsby-starter#119]

**Comment by Mylio-chang** [comment]
1. order.json 支援 toggling for using antd table inline filter or use our admin resource ok
2. schema 先以當前 useAntdTable 可以吃的格式為準，再去考慮跟當前 table schema 的相容性，理論上差異不大，都是對應了 antd table ok
3. column 一樣要支援 customType, dataType 讓 project 自己 render // ok
4. 注意 go to detail routing 與 filter state maintain // 若不行或太複雜就走開新分頁
5. create button, delete button

-> future: refactor Resource first.
現有 Resource 要上移一層，包含 renderCreate / renderCustom 等，下面 include `ResourceTable` `InlineResourceTable`
ResourceTable 即為現有 Table 實作
