### ISSUE TITLE
[fix] GA 後台沒有看到賣出的商品數量、價格（但是總覽有總收益）

### ISSUE THREAD

**Issue by Mylio-chang** [revtel/gatsby-starter#132]
<img width="1039" alt="截圖 2022-03-11 下午5 14 49" src="https://user-images.githubusercontent.com/32530956/158096140-ac7e07e8-f65d-4046-8a6b-59d4a2ceee8e.png">
<img width="677" alt="截圖 2022-03-11 下午5 14 21" src="https://user-images.githubusercontent.com/32530956/158096146-0ae3a2a5-f471-4052-9632-90c2b2421578.png">

**Comment by Mylio-chang** [comment]
https://github.com/revtel/rev.sdk.js/issues/82

**Comment by guychienll** [comment]
code in sdk
