### ISSUE TITLE
[feat] singleton site config

### ISSUE THREAD

**Issue by whitedogg13** [revtel/gatsby-starter#21]

**Comment by whitedogg13** [comment]
steps
- create a new collection called `app_config`, to host all the singleton configurations for a site / app
- each record contains only `name` and `value`, the `name` refers to the type, such as `product_category` or `article_category` or `home_carousel`
- in admin list view, only show name / created / updated
- in admin detail view, use different json schemas for different names
- in ec site, use outlet to spread out the change:
  - fire fetch operations in app initialization
  - once the records are back, update the corresponding outlets

**Comment by whitedogg13** [comment]
dev in this branch: [singleton-site-config](https://github.com/revtel/gatsby-starter/tree/singleton-site-config)

**Comment by whitedogg13** [comment]
Cache all documents in `site` collection to `s3`, and `hit s3 url` during app initialization, it's much faster

**Comment by Mylio-chang** [comment]
branch has been merged to pokemon, also fix for backPath (update sdk version)
