### ISSUE TITLE
[doc] add document for new collections setup

### ISSUE THREAD

**Issue by whitedogg13** [revtel/gatsby-starter#30]

**Comment by whitedogg13** [comment]
Hi @ula, please help on this one!

I think you have the freshest memory since you just finished the nfcmaker.io set-up. Thanks!

**Comment by ulayab** [comment]
Hi @whitedogg13 ,
Does the `new collections step` means the whole project setup steps?

**Comment by whitedogg13** [comment]
@ulayab yes, it will be better

**Comment by ulayab** [comment]
Hi @whitedogg13,
I just done a readme on `main` branch, please take a glance in your free time, thanks🙏  
https://github.com/revtel/gatsby-starter/blob/main/README.md

**Comment by whitedogg13** [comment]
@ulayab beyond this, we also need to mention how to use rev.console, such as:
- create jstorage collections, and set-up their permissions
- create issuers

**Comment by ulayab** [comment]
(PR to main), reviewer: Richie, Mylio
