### ISSUE TITLE
[build] deploy actions design

### ISSUE THREAD

**Issue by whitedogg13** [revtel/gatsby-starter#31]
Per my understanding, in workflow_dispatch, we should be able to select the branch we'd like to use, so we don't need to hard-code the "pokemon" into the github actions.

So, the .yml file name doesn't need to contain "pokemon" as well, which allow this action can be used in projects without modification.

**Comment by whitedogg13** [comment]
check #38

**Comment by guychienll** [comment]
merged pull request and done the issue should be closed
