### ISSUE TITLE
[fix] rev-rename-field default hidden 為 true

### ISSUE THREAD

**Issue by Mylio-chang** [revtel/gatsby-starter#35]

**Comment by guychienll** [comment]
it's default value is true already in pokemon branch , would release it in this friday for 4n

**Comment by Mylio-chang** [comment]
@guychienll hi ha, nope, it's not the default reference implementation of product.json in starter.
what the issue describes is the default props in rev.sdk.js (the custom form component's props) / so maybe this issue should be opened in rev.sdk.js and with more detailed description. (but i'll just leave it here for now.)

**Comment by guychienll** [comment]
got it

**Comment by guychienll** [comment]
hi @Mylio-chang 
this one would update sdk for follow change 
```
function RevRenameImage(props: any) {
  let {schema, uiSchema, formData} = props;

  if (typeof uiSchema.hidden === 'undefined') {
    return null;
  }

  if (uiSchema.hidden) {
    return null;
  }

  return (
    <div
      style={{
        margin: '10px 0',
        maxWidth: 800,
      }}>
      <p style={{marginBottom: 10}}>{schema.title}</p>
      <Input disabled value={formData} />
    </div>
  );
}


```

**Comment by Mylio-chang** [comment]
@guychienll 
i may write like this: (though they're basically the same. / no action required
```
  if (typeof uiSchema.hidden === 'undefined' || uiSchema.hidden) {
    return null;
  }
```
