### ISSUE TITLE
[fix] register

### ISSUE THREAD

**Issue by Mylio-chang** [revtel/gatsby-starter#45]
- [x] user 已存在，api 400， ui 沒有失敗訊息並且開始倒數
    <img width="300" alt="截圖 2022-01-18 下午1 38 56" src="https://user-images.githubusercontent.com/32530956/149877506-26682753-de21-4f92-b108-e0519750a3f6.png">
- [x] 一般 user 註冊完成後，再按登入，登入成功後會停留在註冊成功的畫面（但其實已經登入成功） -> 是否登入成功一率導至 profile page?

**Comment by guychienll** [comment]
this issue's change would apply on rev.sdk.js

**Comment by guychienll** [comment]
https://github.com/revtel/rev.sdk.js/issues/39
