### ISSUE TITLE
[fix] profile 變更 email 一點開就顯示 02:00 （無倒數）

### ISSUE THREAD

**Issue by Mylio-chang** [revtel/gatsby-starter#48]
然後按下寄送驗證信後，倒數是從 03:00 開始

還沒寄信不應顯示倒數 -> 寄信後顯示倒數，倒數結束 button enable + 倒數消失

至信箱點驗證後，更改成功頁面下方：「後續請使用新信箱做登入」-> ？這句移掉，它不是用信箱登入～

<img width="786" alt="截圖 2022-01-19 上午11 54 43" src="https://user-images.githubusercontent.com/32530956/150061255-7d49266a-d55b-438d-8ce4-1f9e53c704c6.png">
<img width="726" alt="截圖 2022-01-19 上午11 56 03" src="https://user-images.githubusercontent.com/32530956/150061218-d72d523f-3d16-4dc0-bacc-e3d5d6224810.png">
<img width="1248" alt="截圖 2022-01-19 下午3 07 31" src="https://user-images.githubusercontent.com/32530956/150081308-a91ec35e-b59d-4f0e-afc3-015f7431c901.png">

**Comment by guychienll** [comment]
done
