### ISSUE TITLE
[question] the renderCustomSection for ProfileLayout / CheckoutLayout looks weird

### ISSUE THREAD

**Issue by whitedogg13** [revtel/gatsby-starter#73]

**Comment by Mylio-chang** [comment]
oh, yes, we don't need that `_renderCustomSection`, we only need `renderCustomSection`
this will be fix before next 4N release

**Comment by Mylio-chang** [comment]
oops, nope, we don't need renderCustomSection in CheckoutLayout actually.
and _renderCustomSection is not in use (and no need) in ProfileLayout.
