### ISSUE TITLE
4N2207 issue

### ISSUE THREAD

**Issue by Mylio-chang** [revtel/gatsby-starter#84]

**Comment by guychienll** [comment]
- 登入方式為 default 時 profile 是否該呈現 登入方式欄位 ？
- reset email issues → 後端寄信 forgot-password
- 能看見本月營收，本月訂單數，且數值正確 → 營收錯了
- 5 digit popup confirm disabled

**Comment by guychienll** [comment]
如果從原來 profile 的 info 搬進 private profile 記得要做 data migration
