### ISSUE TITLE
[refactor] add AppActions for projects

### ISSUE THREAD

**Issue by Mylio-chang** [revtel/gatsby-starter#93]
project 有要加的 actions 都加在 customAppActions
discussion: 是否要另外 import 或者也放在 actions outlet 裡？

**Comment by guychienll** [comment]
目前 naming 為 CustomActions 
並且尚未放於 actions outet 裡，
預期使用會直接 import

**Comment by whitedogg13** [comment]
add `src/AppActions/custom.js`, like this:

```javascript
const customAppActions = {}
export customAppActions
```

and modify `src/App` to accept these actions:

```javascript
import * as AppActions from 'AppActions'
import * as CustomActions from 'AppActions/custom'

AppActionOutlet.update({
  ...AppActions,
  ...CustomActions,
});
```

So `CustomActions` serves two objectives:
- provide project only actions
- override default `AppActions`, if `Plugin` is not enough

**Comment by guychienll** [comment]
https://github.com/revtel/gatsby-starter/pull/111
