### ISSUE TITLE
site-config + um toggling

### ISSUE THREAD

**Issue by Mylio-chang** [revtel/gatsby-starter#94]
new singleton: site-config + um toggling

**Comment by guychienll** [comment]
will do this after backend api for s3 storage

**Comment by guychienll** [comment]
pending this https://github.com/revtel/gatsby-starter/issues/32

**Comment by whitedogg13** [comment]
provide `src/AppPages/um.js`, point **ALL** routes into `src/Templates/UnderMaintain`, and update `gatsby-node.js` to point to it.

**Comment by Mylio-chang** [comment]
<img width="1171" alt="截圖 2022-03-16 上午9 44 46" src="https://user-images.githubusercontent.com/32530956/158500141-f94e776f-6c14-40cf-b23b-172cebf7f7dd.png">
