### ISSUE TITLE
social signin 若無 email，強制 user 填寫、驗證

### ISSUE THREAD

**Issue by Mylio-chang** [revtel/gatsby-starter#96]
問題：部分 user 當時 social 註冊時並無 email，導致雖然註冊完成，但是沒有 email 可以連絡人、不知道是誰

處理：user 一但想要購物結帳，就必須驗證 email，做法上傾向加入購物車時就確認是否無 email，導至 profile 頁面讓 user 在 profile 頁面進行驗證。
profile 頁面針對 email 未填寫，可 always 顯示紅色文字提醒

**Comment by guychienll** [comment]
got it

**Comment by guychienll** [comment]
https://github.com/revtel/rev.sdk.js/pull/64

**Comment by guychienll** [comment]
需要更新 starter 跟 sdk 版本
